import { Database, Destination } from "@/types";

const DESTINATIONS_DATA: Destination[] = [
  {
    id: "1",
    title: "Manali to Leh Highway",
    region: "Himalayas",
    days: 5,
    priceFrom: 12000,
    rating: 4.8,
    reviews: 342,
    scene: "mountain",
    blurb: "One of the world's highest motorable passes. Stark beauty.",
    area: "Himachal Pradesh, Ladakh",
    hidden: false,
  },
  {
    id: "2",
    title: "Char Dham Yatra",
    region: "Himalayas",
    days: 7,
    priceFrom: 18000,
    rating: 4.7,
    reviews: 287,
    scene: "temple",
    blurb: "The sacred circuit of temples. Spiritual journey.",
    area: "Uttarakhand",
    hidden: false,
  },
  {
    id: "3",
    title: "Rajasthan Heritage Trail",
    region: "Rajasthan",
    days: 6,
    priceFrom: 13000,
    rating: 4.6,
    reviews: 421,
    scene: "heritage",
    blurb: "Palaces, forts, and desert. Royal splendor.",
    area: "Rajasthan",
    hidden: false,
  },
  {
    id: "4",
    title: "Kerala Backwaters",
    region: "Deep South",
    days: 4,
    priceFrom: 11000,
    rating: 4.9,
    reviews: 513,
    scene: "backwater",
    blurb: "Serene waters and green shores. Pure tranquility.",
    area: "Kerala",
    hidden: false,
  },
  {
    id: "5",
    title: "Nepal & Bhutan Crossing",
    region: "Nepal & Bhutan",
    days: 8,
    priceFrom: 22000,
    rating: 4.7,
    reviews: 198,
    scene: "monastery",
    blurb: "Two kingdoms in one journey. Himalayan magic.",
    area: "Nepal, Bhutan",
    hidden: false,
  },
  {
    id: "6",
    title: "Offbeat Northeast",
    region: "Northeast",
    days: 5,
    priceFrom: 14000,
    rating: 4.5,
    reviews: 156,
    scene: "village",
    blurb: "Unexplored lands, tribal cultures, living traditions.",
    area: "Meghalaya, Assam, Nagaland",
    hidden: false,
  },
  {
    id: "7",
    title: "Andaman Islands",
    region: "Andaman & Nicobar",
    days: 5,
    priceFrom: 16000,
    rating: 4.8,
    reviews: 287,
    scene: "beach",
    blurb: "Coral reefs, turquoise waters, island escape.",
    area: "Andaman & Nicobar Islands",
    hidden: false,
  },
  {
    id: "8",
    title: "Spiti Valley Circuit",
    region: "Himalayas",
    days: 6,
    priceFrom: 15000,
    rating: 4.6,
    reviews: 134,
    scene: "monastery",
    blurb: "High desert, ancient monasteries, raw landscape.",
    area: "Himachal Pradesh",
    hidden: false,
  },
];

export function seedDatabase(): Database {
  return {
    destinations: DESTINATIONS_DATA,
    guides: [
      {
        id: "g1",
        name: "Raj Kumar",
        city: "Shimla",
        phone: "+91-9876543210",
        rating: 4.8,
        reviews: 45,
        verified: true,
        languages: ["English", "Hindi", "Himachali"],
      },
      {
        id: "g2",
        name: "Priya Sharma",
        city: "Kochi",
        phone: "+91-9876543211",
        rating: 4.9,
        reviews: 63,
        verified: true,
        languages: ["English", "Hindi", "Malayalam"],
      },
      {
        id: "g3",
        name: "Vikram Singh",
        city: "Jaipur",
        phone: "+91-9876543212",
        rating: 4.7,
        reviews: 52,
        verified: true,
        languages: ["English", "Hindi", "Marwari"],
      },
      {
        id: "g4",
        name: "Ananya Das",
        city: "Shillong",
        phone: "+91-9876543213",
        rating: 4.6,
        reviews: 38,
        verified: true,
        languages: ["English", "Hindi", "Khasi"],
      },
      {
        id: "g5",
        name: "Suresh Reddy",
        city: "Hyderabad",
        phone: "+91-9876543214",
        rating: 4.8,
        reviews: 41,
        verified: true,
        languages: ["English", "Hindi", "Telugu"],
      },
    ],
    drivers: [
      {
        id: "d1",
        name: "Mohit Patel",
        vehicle: "Innova Crysta",
        phone: "+91-9876543220",
        rating: 4.9,
        verified: true,
      },
      {
        id: "d2",
        name: "Deepak Yadav",
        vehicle: "Toyota Fortuner",
        phone: "+91-9876543221",
        rating: 4.7,
        verified: true,
      },
      {
        id: "d3",
        name: "Arun Kumar",
        vehicle: "Maruti Vitara Brezza",
        phone: "+91-9876543222",
        rating: 4.8,
        verified: true,
      },
    ],
    stays: [
      {
        id: "s1",
        title: "Mountain Lodge Manali",
        region: "Himalayas",
        city: "Manali",
        type: "Lodge",
        pricePerNight: 2500,
        rating: 4.6,
        reviews: 87,
        amenities: ["WiFi", "Hot Water", "Restaurant", "Garden"],
        verified: true,
      },
      {
        id: "s2",
        title: "Houseboat Kerala",
        region: "Deep South",
        city: "Alleppey",
        type: "Houseboat",
        pricePerNight: 3500,
        rating: 4.8,
        reviews: 142,
        amenities: ["Kitchen", "Bedroom", "Deck", "Guide"],
        verified: true,
      },
      {
        id: "s3",
        title: "Heritage Palace Jaipur",
        region: "Rajasthan",
        city: "Jaipur",
        type: "Hotel",
        pricePerNight: 4000,
        rating: 4.7,
        reviews: 156,
        amenities: ["Pool", "Restaurant", "Spa", "WiFi"],
        verified: true,
      },
    ],
    bookings: [],
    reviews: [],
    auditLog: [],
    settings: {
      siteName: "Deshatan",
      supportEmail: "support@deshatan.com",
      paymentMethods: ["Card", "UPI", "Bank Transfer"],
    },
  };
}
